### ISSUE TITLE
the login process is kind of scary

### ISSUE THREAD

**Issue by joshk6** [plnkr/feedback#248]
You seem to be asking for access to "personal user data" consisting of "email addresses".  Maybe that just means the email address I am using to log in, but not using oauth2 that much I"m not really sure what it really means, if anything other than access to teh email address I am using to sign up.

I'm guessing this oauth page is controlled by GitHub, but stilll...

**Comment by ggoodman** [comment]
Hi @joshk6, indeed the login requests access to email addresses in addition to the public information provided by OpenID-ish providers like Github.

I request the email address so that it is possible to correlate social identities across platforms so that users don't accidentally create two accounts by forgetting which social login they originally used.

**Comment by joshk6** [comment]
Agree, I kind of feel the invasion of my privacy doesn’t isn’t really justified by the desire to avoid creating two accounts.
