### ISSUE TITLE
Preview keeps `Loading...` on alpha and old version, using Chrome

### ISSUE THREAD

**Issue by andesappal** [plnkr/feedback#474]
I can't see the preview.

**Comment by andesappal** [comment]
![image](https://user-images.githubusercontent.com/54340176/66661919-37bfc700-ec1e-11e9-8b07-cbd12f74f453.png)

**Comment by ggoodman** [comment]
Hello @andesappal, if you click on the `Console` in the bottom right, you would see a SystemJS error indicating that rxjs/operators.js couldn't be found. This is because the Plunk you're trying to load was not created in a future-proof way.

Duplicate of #61. Please see the potential solution linked there.
