### ISSUE TITLE
Failed to load my own files as ES6-modules

### ISSUE THREAD

**Issue by ivan-enzhaev** [plnkr/feedback#569]
Failed to load my own files as ES6-modules: https://plnkr.co/edit/bjAl7TXmY9CzzQl5

External module works fine:

```js
<body>
    <script async src="https://unpkg.com/es-module-shims@1.5.5/dist/es-module-shims.js"></script>

    <script type="importmap">
        {
            "imports": {
                "gl-matrix": "https://cdn.skypack.dev/gl-matrix@3.4.3"
            }
        }
    </script>

    <script type="module" src="src/main.js"></script>
</body>
```

main.js

```js
import * as glMatrix from "gl-matrix";
console.log(glMatrix.mat4.create());
```

But my module doesn't work: `Failed to load resource: the server responded with a status of 404`

my-class.js

```js

export default class MyClass {
    constructor() {
        console.log("My Class");
    }
}
```

main.js

```js
import MyClass from "./my-class";
new MyClass();
```

**Comment by ivan-enzhaev** [comment]
This only works:

```js
import MyClass from "./my-class";
new MyClass();
```

if you add the ".js" extension:

```js
import MyClass from "./my-class.js";
new MyClass();
```

For me, this is the solution.

**Comment by ggoodman** [comment]
I'm going to close this because as you noted, browser module resolution will _never_ infer a file's extension. This is a convenience introduced by bundlers where the set of possible files satisfying a prefix can be discovered on the filesystem. On the web, the browser won't make a sequence of requests to attempt to 'find' a file matching the prefix in the specifier.
